added gitreport

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -94,7 +94,7 @@ jobs:
       #  cd tests/e2e && npm run test setup.spec.ts
       - name: Running the e2e tests
         run: |
-          cd tests/e2e && npm run test admin.spec.ts
+          cd tests/e2e && npm run admins.spec.ts
 
         env:
           CI: true
@@ -106,29 +106,29 @@ jobs:
           CUSTOMER_PASSWORD: ${{ secrets.VENDOR_PASSWORD }}
           BASE_URL: ${{ secrets.BASE_URL }}
 
-      - name: See result directory
-        run: |
-          cd tests/e2e
-          ls
-          cd tests/e2e/playwright-report
-          ls
+      # - name: See result directory
+      #   run: |
+      #     cd tests/e2e
+      #     ls
+      #     cd tests/e2e/playwright-report
+      #     ls
 
-      - name: Generate Test Report
-        uses: phoenix-actions/test-reporting@v8
-        id: test-report # Set ID reference for step
-        if: success() || failure() # run this step even if previous step failed
-        with:
-          name: e2e tests result # Name of the check run which will be created
-          path: tests/e2e/playwright-report/results.xml # Path to test results
-          reporter: jest-junit
-          only-summary: "false" # Allows you to generate only the summary.
-          list-suites: "all" # Limits which test suites are listed: 'all', 'failed'
-          list-tests: "all" # Limits which test cases are listed: 'all','failed', 'none'
-          fail-on-error: "true" # Set action as failed if test report contains any failed test
+      # - name: Generate Test Report
+      #   uses: phoenix-actions/test-reporting@v8
+      #   id: test-report # Set ID reference for step
+      #   if: success() || failure() # run this step even if previous step failed
+      #   with:
+      #     name: e2e tests result # Name of the check run which will be created
+      #     path: tests/e2e/playwright-report/results.xml # Path to test results
+      #     reporter: jest-junit
+      #     only-summary: "false" # Allows you to generate only the summary.
+      #     list-suites: "all" # Limits which test suites are listed: 'all', 'failed'
+      #     list-tests: "all" # Limits which test cases are listed: 'all','failed', 'none'
+      #     fail-on-error: "true" # Set action as failed if test report contains any failed test
 
-      - name: Test results
-        run: |
-          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
+      # - name: Test results
+      #   run: |
+      #     echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
 
       - name: Archive playwright artifacts (screenshots, HTML snapshots, Reports)
         uses: actions/upload-artifact@v3
@@ -139,25 +139,25 @@ jobs:
           if-no-files-found: ignore
           retention-days: 30
 
-  # publishTestResults:
-  #   name: Publish Test Results
-  #   runs-on: ubuntu-latest
-  #   if: always()
-  #   steps:
-  # - name: Download artifacts
-  #   uses: actions/download-artifact@v2
-  #   id: download
+  publishTestResults:
+    name: Publish Test Results
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+    - name: Download artifacts
+      uses: actions/download-artifact@v2
+      id: download
 
-  # - name: Publish HTML report to GH Pages
-  #   if: always() # We want this to always run, even if test fail prior to this step running
-  #   uses: peaceiris/actions-gh-pages@v3.7.3
-  #   with:
-  #     github_token: ${{ secrets.GITHUB_TOKEN }}
-  #     publish_dir: ${{steps.download.outputs.download-path}} # This is where index.html will be output
-  #     keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
-  #     user_name: "github-actions[bot]" # This will be the username that gets stamped in the repo commit
-  #     user_email: "github-actions[bot]@users.noreply.github.com" # This will be the user email that gets stamped in the repo commit
+    - name: Publish HTML report to GH Pages
+      if: always() # We want this to always run, even if test fail prior to this step running
+      uses: peaceiris/actions-gh-pages@v3.7.3
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        publish_dir: ${{steps.download.outputs.download-path}} # This is where index.html will be output
+        keep_files: true # Set this to true to make sure we don't wipe out the other content in GitHub Pages
+        user_name: "github-actions[bot]" # This will be the username that gets stamped in the repo commit
+        user_email: "github-actions[bot]@users.noreply.github.com" # This will be the user email that gets stamped in the repo commit
 
-  # - name: Test results
-  #   run: |
-  #     echo "url is https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#/*/}"
+    - name: Test results
+      run: |
+        echo "url is https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#/*/}"
