added gitreport

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -113,35 +113,35 @@ jobs:
       #     cd tests/e2e/playwright-report
       #     ls
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        if: always() # always run even if the previous step fails
-        with:
-          report_paths: 'tests/e2e/playwright-report/results.xml'
-          include_passed: true,
-          check_retries: true,
-          detailed_summary: true,
-
-
-
-
-
-      # - name: Generate Test Report
-      #   uses: phoenix-actions/test-reporting@v8
-      #   id: test-report # Set ID reference for step
-      #   if: success() || failure() # run this step even if previous step failed
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@v3
+      #   if: always() # always run even if the previous step fails
       #   with:
-      #     name: e2e tests result # Name of the check run which will be created
-      #     path: tests/e2e/playwright-report/results.xml # Path to test results
-      #     reporter: jest-junit
-      #     only-summary: "false" # Allows you to generate only the summary.
-      #     list-suites: "all" # Limits which test suites are listed: 'all', 'failed'
-      #     list-tests: "all" # Limits which test cases are listed: 'all','failed', 'none'
-      #     fail-on-error: "true" # Set action as failed if test report contains any failed test
+      #     report_paths: 'tests/e2e/playwright-report/results.xml'
+      #     include_passed: true,
+      #     check_retries: true,
+      #     detailed_summary: true,
 
-      # - name: Test results
-      #   run: |
-      #     echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
+
+
+
+
+      - name: Generate Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report # Set ID reference for step
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: e2e tests result # Name of the check run which will be created
+          path: tests/e2e/playwright-report/results.xml # Path to test results
+          # reporter: jest-junit
+          only-summary: "false" # Allows you to generate only the summary.
+          list-suites: "all" # Limits which test suites are listed: 'all', 'failed'
+          list-tests: "all" # Limits which test cases are listed: 'all','failed', 'none'
+          fail-on-error: "true" # Set action as failed if test report contains any failed test
+
+      - name: Test results
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
 
       - name: Archive playwright artifacts (screenshots, HTML snapshots, Reports)
         uses: actions/upload-artifact@v3
