added gitreport

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -106,22 +106,22 @@ jobs:
           CUSTOMER_PASSWORD: ${{ secrets.VENDOR_PASSWORD }}
           BASE_URL: ${{ secrets.BASE_URL }}
 
-      # - name: Generate Test Report
-      #   uses: phoenix-actions/test-reporting@v8
-      #   id: test-report               # Set ID reference for step
-      #   if: success() || failure()    # run this step even if previous step failed
-      #   with:
-      #     name: e2e tests result            # Name of the check run which will be created
-      #     path: artifacts/reports/junit.xml    # Path to test results
-      #     reporter: jest-junit
-      #     only-summary: 'false' # Allows you to generate only the summary.
-      #     list-suites: 'all'  # Limits which test suites are listed: 'all', 'failed'
-      #     list-tests: 'all'       # Limits which test cases are listed: 'all','failed', 'none'
-      #     fail-on-error: 'true'   # Set action as failed if test report contains any failed test
+      - name: Generate Test Report
+        uses: phoenix-actions/test-reporting@v8
+        id: test-report               # Set ID reference for step
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: e2e tests result            # Name of the check run which will be created
+          path: artifacts/playwright-report/results.xml    # Path to test results
+          reporter: jest-junit
+          only-summary: 'false' # Allows you to generate only the summary.
+          list-suites: 'all'  # Limits which test suites are listed: 'all', 'failed'
+          list-tests: 'all'       # Limits which test cases are listed: 'all','failed', 'none'
+          fail-on-error: 'true'   # Set action as failed if test report contains any failed test
 
-      # - name: Test results
-      #   run: |
-      #     echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
+      - name: Test results
+        run: |
+          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
 
 
       - name: Archive playwright artifacts (screenshots, HTML snapshots, Reports)
